---
- name: "Check system"
  ansible.builtin.assert:
    that: ansible_os_family == "Windows"

- name: "Check chocolatey"
  ansible.builtin.stat:
    path: C:\ProgramData\chocolatey
  register: chocolatey_exists

- name: 'Install chocolatey'
  ansible.windows.win_powershell:
    script: |
      Set-ExecutionPolicy Bypass -Scope Process -Force;
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
      iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  when: not chocolatey_exists
