---
- name: Verify
  hosts: all
  become: true
  vars:
    vscode_install_insiders: true
  tasks:
    - name: Verify apt key
      ansible.builtin.stat:
        path: /etc/apt/trusted.gpg.d/microsoft.asc
        checksum_algorithm: sha256
      register: apt_key
      failed_when: "apt_key.stat.checksum != \
        '2cfd20a306b2fa5e25522d78f2ef50a1f429d35fd30bd983e2ebffc2b80944fa'"

    - name: Verify apt repository
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/vscode.list
        checksum_algorithm: sha256
      register: apt_repository
      failed_when: "apt_repository.stat.checksum != \
        '082a1dbfa9fc35b97dbc56c53e5008fbb48b2d031c2ae3c670639e393e349f8a'"

    - name: Verify code package
      ansible.builtin.package:
        name: code
        state: present
      check_mode: true

    - name: Verify code-insiders package
      ansible.builtin.package:
        name: code-insiders
        state: present
      check_mode: true
